// Constantes partagées — GETRAD Web

export const REGIONS = [
  'Auvergne-Rhône-Alpes',
  'Bourgogne-Franche-Comté',
  'Bretagne',
  'Centre-Val de Loire',
  'Corse',
  'Grand Est',
  'Hauts-de-France',
  'Île-de-France',
  'Normandie',
  'Nouvelle-Aquitaine',
  'Occitanie',
  'Pays de la Loire',
  "Provence-Alpes-Côte d'Azur",
];

export const LANGUAGES = [
  'Français',
  'Anglais',
  'Espagnol',
  'Arabe',
  'Chinois (Mandarin)',
  'Allemand',
  'Italien',
  'Portugais',
  'Russe',
  'Japonais',
  'Coréen',
  'Turc',
  'Polonais',
  'Néerlandais',
  'Suédois',
  'Norvégien',
  'Danois',
  'Grec',
  'Hébreu',
  'Hindi',
  'Bengali',
  'Vietnamien',
  'Thaï',
  'Roumain',
  'Ukrainien',
  'Tchèque',
  'Hongrois',
  'Bulgare',
  'Serbe',
  'Croate',
];

export const SPECIALTIES = [
  'Juridique',
  'Médical',
  'Financier',
  'Technique',
  'Commercial',
  'Conférence',
  'Littéraire',
  'Scientifique',
  'Diplomatique',
  'Audiovisuel',
  'Marketing',
  'IT / Logiciel',
  'Tourisme',
  'Éducation / Formation',
];

export const SERVICES = [
  { id: 'interpretation_simultanee', label: 'Interprétation simultanée' },
  { id: 'interpretation_consecutive', label: 'Interprétation consécutive' },
  { id: 'interpretation_liaison', label: 'Interprétation de liaison' },
  { id: 'interpretation_presentiel', label: 'Interprétation en présentiel' },
  { id: 'interpretation_distance', label: 'Interprétation à distance (visio / téléphone)' },
  { id: 'traduction_documents', label: 'Traduction de documents' },
  { id: 'traduction_site_web', label: 'Traduction de sites web / applications' },
  { id: 'localisation', label: 'Localisation linguistique' },
  { id: 'traduction_assermentee', label: 'Traduction assermentée' },
  { id: 'relecture_revision', label: 'Relecture et révision' },
  { id: 'transcription', label: 'Transcription audio' },
  { id: 'sous_titrage', label: 'Sous-titrage' },
  { id: 'voice_over', label: 'Voice-over / doublage' },
  { id: 'post_edition', label: 'Post-édition (traduction automatique)' },
  { id: 'gestion_projet', label: 'Gestion de projets linguistiques' },
  { id: 'guide_touristique', label: 'Guide touristique multilingue' },
  { id: 'formation_langues', label: 'Formation en langues' },
];

export const FRENCH_CITIES = [
  'Ajaccio', 'Aix-en-Provence', 'Amiens', 'Angers', 'Annecy', 'Antibes',
  'Argenteuil', 'Arles', 'Aubagne', 'Aulnay-sous-Bois', 'Avignon',
  'Besançon', 'Béziers', 'Bordeaux', 'Boulogne-Billancourt', 'Brest',
  'Caen', 'Cannes', 'Clermont-Ferrand', 'Colombes', 'Créteil',
  'Dijon', 'Dunkerque',
  'Fort-de-France', 'Grenoble',
  'La Rochelle', 'Le Havre', 'Le Mans', 'Lens', 'Limoges', 'Lille', 'Lyon',
  'Marseille', 'Metz', 'Montpellier', 'Montreuil', 'Mulhouse',
  'Nancy', 'Nantes', 'Nîmes', 'Nice', 'Noisy-le-Grand',
  'Orléans',
  'Paris', 'Pau', 'Perpignan', 'Pointe-à-Pitre', 'Poitiers',
  'Reims', 'Rennes', 'Rouen', 'Rueil-Malmaison',
  'Saint-Denis', 'Saint-Étienne', 'Saint-Paul', 'Strasbourg', 'Saint-Nazaire',
  'Toulon', 'Toulouse', 'Tours', 'Tourcoing', 'Troyes',
  'Valenciennes', 'Versailles', 'Villeurbanne',
];

export const BOOKING_STATUS_LABELS = {
  pending: 'En attente',
  accepted: 'Acceptée',
  confirmed: 'Confirmée',
  refused: 'Refusée',
  rejected: 'Refusée',
  completed: 'Terminée',
  cancelled: 'Annulée',
};

export const BOOKING_STATUS_COLORS = {
  pending: 'bg-yellow-100 text-yellow-800',
  accepted: 'bg-green-100 text-green-800',
  confirmed: 'bg-green-100 text-green-800',
  refused: 'bg-red-100 text-red-800',
  rejected: 'bg-red-100 text-red-800',
  completed: 'bg-gray-100 text-gray-700',
  cancelled: 'bg-gray-100 text-gray-700',
};
